### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by kenpem** [samyk/easel-driver#11]
Almost certainly my fault as I'm not Linux-flavoured enough to understand these things! Using the curl install, I end up with 
```
+ tail screenlog.0
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1340:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '0.0.0.0',
  port: 1438
}
+ echo \n\nDone! Easel driver running in background. Run `screen -r` to bring it to foreground.
```
I've tried the curl command as posted, and also as a sudo command, same result. What I am doing wrong? Any help much appreciated! My CNC 3018 is built and ready to go... I just need Easel to talk to it :)

**Comment by samyk** [comment]
`EADDRINUSE` means something is already listening on that port. Are you sure it's not already running?

What if you `screen -r`? If nothing opens, try, `lsof -n | grep :1438' and paste output to see what's listening on the port (you may need to `sudo apt-get -y install lsof`)

**Comment by kenpem** [comment]
Sorry for the delay in response.

I ended up retiring that laptop and setting up a dedicated Raspberry PI to run the CNC. The curl install worked flawlessly, and as I type this, my 3018 is busy carving a clock face.

You rock.

**Comment by samyk** [comment]
Awesome! Thanks for the update.
