### ISSUE TITLE
Easel Driver crashed and will not load

### ISSUE THREAD

**Issue by shortcircuit48** [samyk/easel-driver#12]
I am a novice and hope this info will be ok.  I have been using the driver for some time on Linux with no problem.  Yesterday my router just stopped and failed to respond.  I have attempted to reload numerous times using different hard drives and totally wiping my operating system to no avail.  Can you please help.  I attach log
/home/hamish/.npm/_logs/2020-10-28T10_06_03_772Z-debug.log
[2020-10-28T10_24_58_934Z-debug.log](https://github.com/samyk/easel-driver/files/5451149/2020-10-28T10_24_58_934Z-debug.log)

**Comment by shortcircuit48** [comment]
I followed instruction you posted and now up and running.  Thanks

**Comment by samyk** [comment]
Awesome, which instructions? Just want to ensure whatever it is is resolved in the repo.

**Comment by shortcircuit48** [comment]
Instructions as per your post in #13 to Steven Wells.  Again thanks
