### ISSUE TITLE
Install Failure

### ISSUE THREAD

**Issue by stevewells20** [samyk/easel-driver#13]
Using the the command `curl https://raw.githubusercontent.com/samyk/easel-driver/master/easel-driver.sh | sh -x`, Installation fails. Below is the stacktrace from where is starts going wrong.

System: Thinkpad, Intel i7-6800
OS: Ubuntu 20.04, fairly fresh and unmodified (2 weeks old)

> + nvm_tree_contains_path /home/steven/.nvm /home/steven/.nvm/versions/node/v14.15.0
> + [ -n Now using node v14.15.0 (npm v6.14.8) ]
> + nvm_echo Now using node v14.15.0 (npm v6.14.8)
> + command printf %s\n Now using node v14.15.0 (npm v6.14.8)
> Now using node v14.15.0 (npm v6.14.8)
> + npm install
> npm WARN deprecated json3@3.3.2: Please use the native JSON object instead of JSON 3
> npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
> 
> > @serialport/bindings@2.0.8 install /home/steven/easel-driver/node_modules/@serialport/bindings
> > prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild
> 
> prebuild-install WARN install No prebuilt binaries found (target=14.15.0 runtime=node arch=x64 libc= platform=linux)
> make: Entering directory '/home/steven/easel-driver/node_modules/@serialport/bindings/build'
>   CXX(target) Release/obj.target/bindings/src/serialport.o
> ../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Open(Nan::NAN_METHOD_ARGS_TYPE)’:
> ../src/serialport.cpp:78:69: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
>    78 |   uv_queue_work(uv_default_loop(), req, EIO_Open, (uv_after_work_cb)EIO_AfterOpen);
>       |                                                                     ^~~~~~~~~~~~~
> ../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Update(Nan::NAN_METHOD_ARGS_TYPE)’:
> ../src/serialport.cpp:135:71: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
>   135 |   uv_queue_work(uv_default_loop(), req, EIO_Update, (uv_after_work_cb)EIO_AfterUpdate);
>       |                                                                       ^~~~~~~~~~~~~~~
> ../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Close(Nan::NAN_METHOD_ARGS_TYPE)’:
> ../src/serialport.cpp:175:70: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
>   175 |   uv_queue_work(uv_default_loop(), req, EIO_Close, (uv_after_work_cb)EIO_AfterClose);
>       |                                                                      ^~~~~~~~~~~~~~
> ../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Flush(Nan::NAN_METHOD_ARGS_TYPE)’:
> ../src/serialport.cpp:215:70: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
>   215 |   uv_queue_work(uv_default_loop(), req, EIO_Flush, (uv_after_work_cb)EIO_AfterFlush);
>       |                                                                      ^~~~~~~~~~~~~~
> ../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Set(Nan::NAN_METHOD_ARGS_TYPE)’:
> ../src/serialport.cpp:270:68: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
>   270 |   uv_queue_work(uv_default_loop(), req, EIO_Set, (uv_after_work_cb)EIO_AfterSet);
>       |                                                                    ^~~~~~~~~~~~
> ../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Get(Nan::NAN_METHOD_ARGS_TYPE)’:
> ../src/serialport.cpp:314:68: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
>   314 |   uv_queue_work(uv_default_loop(), req, EIO_Get, (uv_after_work_cb)EIO_AfterGet);
>       |                                                                    ^~~~~~~~~~~~
> ../src/serialport.cpp: In function ‘void EIO_AfterGet(uv_work_t*)’:
> ../src/serialport.cpp:329:96: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, Nan::imp::FactoryBase<v8::Boolean>::return_t)’
>   329 |     results->Set(Nan::New<v8::String>("cts").ToLocalChecked(), Nan::New<v8::Boolean>(data->cts));
>       |                                                                                                ^
> In file included from /home/steven/.cache/node-gyp/14.15.0/include/node/node.h:67,
>                  from ../../../nan/nan.h:56,
>                  from ../src/./serialport.h:6,
>                  from ../src/serialport.cpp:1:
> /home/steven/.cache/node-gyp/14.15.0/include/node/v8.h:3670:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’
>  3670 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
>       |                                     ^~~
> /home/steven/.cache/node-gyp/14.15.0/include/node/v8.h:3670:37: note:   candidate expects 3 arguments, 2 provided
> /home/steven/.cache/node-gyp/14.15.0/include/node/v8.h:3673:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’
>  3673 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
>       |                                     ^~~
> /home/steven/.cache/node-gyp/14.15.0/include/node/v8.h:3673:37: note:   candidate expects 3 arguments, 2 provided
> ../src/serialport.cpp:330:96: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, Nan::imp::FactoryBase<v8::Boolean>::return_t)’
>   330 |     results->Set(Nan::New<v8::String>("dsr").ToLocalChecked(), Nan::New<v8::Boolean>(data->dsr));
>       |                                                                                                ^
> In file included from /home/steven/.cache/node-gyp/14.15.0/include/node/node.h:67,
>                  from ../../../nan/nan.h:56,
>                  from ../src/./serialport.h:6,
>                  from ../src/serialport.cpp:1:
> /home/steven/.cache/node-gyp/14.15.0/include/node/v8.h:3670:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’
>  3670 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
>       |                                     ^~~
> /home/steven/.cache/node-gyp/14.15.0/include/node/v8.h:3670:37: note:   candidate expects 3 arguments, 2 provided
> /home/steven/.cache/node-gyp/14.15.0/include/node/v8.h:3673:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’
>  3673 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
>       |                                     ^~~
> /home/steven/.cache/node-gyp/14.15.0/include/node/v8.h:3673:37: note:   candidate expects 3 arguments, 2 provided
> ../src/serialport.cpp:331:96: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, Nan::imp::FactoryBase<v8::Boolean>::return_t)’
>   331 |     results->Set(Nan::New<v8::String>("dcd").ToLocalChecked(), Nan::New<v8::Boolean>(data->dcd));
>       |                                                                                                ^
> In file included from /home/steven/.cache/node-gyp/14.15.0/include/node/node.h:67,
>                  from ../../../nan/nan.h:56,
>                  from ../src/./serialport.h:6,
>                  from ../src/serialport.cpp:1:
> /home/steven/.cache/node-gyp/14.15.0/include/node/v8.h:3670:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’
>  3670 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
>       |                                     ^~~
> /home/steven/.cache/node-gyp/14.15.0/include/node/v8.h:3670:37: note:   candidate expects 3 arguments, 2 provided
> /home/steven/.cache/node-gyp/14.15.0/include/node/v8.h:3673:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’
>  3673 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
>       |                                     ^~~
> /home/steven/.cache/node-gyp/14.15.0/include/node/v8.h:3673:37: note:   candidate expects 3 arguments, 2 provided
> ../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE GetBaudRate(Nan::NAN_METHOD_ARGS_TYPE)’:
> ../src/serialport.cpp:363:76: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
>   363 |   uv_queue_work(uv_default_loop(), req, EIO_GetBaudRate, (uv_after_work_cb)EIO_AfterGetBaudRate);
>       |                                                                            ^~~~~~~~~~~~~~~~~~~~
> ../src/serialport.cpp: In function ‘void EIO_AfterGetBaudRate(uv_work_t*)’:
> ../src/serialport.cpp:378:106: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, Nan::imp::IntegerFactory<v8::Integer>::return_t)’
>   378 |     results->Set(Nan::New<v8::String>("baudRate").ToLocalChecked(), Nan::New<v8::Integer>(data->baudRate));
>       |                                                                                                          ^
> In file included from /home/steven/.cache/node-gyp/14.15.0/include/node/node.h:67,
>                  from ../../../nan/nan.h:56,
>                  from ../src/./serialport.h:6,
>                  from ../src/serialport.cpp:1:
> /home/steven/.cache/node-gyp/14.15.0/include/node/v8.h:3670:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’
>  3670 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
>       |                                     ^~~
> /home/steven/.cache/node-gyp/14.15.0/include/node/v8.h:3670:37: note:   candidate expects 3 arguments, 2 provided
> /home/steven/.cache/node-gyp/14.15.0/include/node/v8.h:3673:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’
>  3673 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
>       |                                     ^~~
> /home/steven/.cache/node-gyp/14.15.0/include/node/v8.h:3673:37: note:   candidate expects 3 arguments, 2 provided
> ../src/serialport.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE Drain(Nan::NAN_METHOD_ARGS_TYPE)’:
> ../src/serialport.cpp:409:70: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
>   409 |   uv_queue_work(uv_default_loop(), req, EIO_Drain, (uv_after_work_cb)EIO_AfterDrain);
>       |                                                                      ^~~~~~~~~~~~~~
> ../src/serialport.cpp: At global scope:
> ../src/serialport.cpp:430:28: warning: unnecessary parentheses in declaration of ‘ToParityEnum’ [-Wparentheses]
>   430 | SerialPortParity NAN_INLINE(ToParityEnum(const v8::Local<v8::String>& v8str)) {
>       |                            ^
> ../src/serialport.cpp:449:30: warning: unnecessary parentheses in declaration of ‘ToStopBitEnum’ [-Wparentheses]
>   449 | SerialPortStopBits NAN_INLINE(ToStopBitEnum(double stopBits)) {
>       |                              ^
> In file included from ../../../nan/nan.h:56,
>                  from ../src/./serialport.h:6,
>                  from ../src/serialport.cpp:1:
> /home/steven/.cache/node-gyp/14.15.0/include/node/node.h:758:43: warning: cast between incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
>   758 |       (node::addon_register_func) (regfunc),                          \
>       |                                           ^
> /home/steven/.cache/node-gyp/14.15.0/include/node/node.h:792:3: note: in expansion of macro ‘NODE_MODULE_X’
>   792 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
>       |   ^~~~~~~~~~~~~
> ../src/serialport.cpp:483:1: note: in expansion of macro ‘NODE_MODULE’
>   483 | NODE_MODULE(serialport, init);
>       | ^~~~~~~~~~~
> make: *** [bindings.target.mk:114: Release/obj.target/bindings/src/serialport.o] Error 1
> make: Leaving directory '/home/steven/easel-driver/node_modules/@serialport/bindings/build'
> gyp ERR! build error 
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/home/steven/.nvm/versions/node/v14.15.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
> gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
> gyp ERR! System Linux 5.4.0-48-generic
> gyp ERR! command "/home/steven/.nvm/versions/node/v14.15.0/bin/node" "/home/steven/.nvm/versions/node/v14.15.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd /home/steven/easel-driver/node_modules/@serialport/bindings
> gyp ERR! node -v v14.15.0
> gyp ERR! node-gyp -v v5.1.0
> gyp ERR! not ok 
> npm WARN Iris@0.3.20 No description
> npm WARN Iris@0.3.20 No repository field.
> npm WARN Iris@0.3.20 No license field.
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! @serialport/bindings@2.0.8 install: `prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the @serialport/bindings@2.0.8 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/steven/.npm/_logs/2020-10-30T19_36_01_531Z-debug.log
>

**Comment by samyk** [comment]
Weird that node-gyp isn't compiling but my guess is that it's related to Node v14 (now that that's LTS -- recently LTS was node v12.

What if you run:
`curl https://raw.githubusercontent.com/samyk/easel-driver/master/easel-driver.sh > easel-driver.sh`

Then modify easel-driver.sh and change these two lines from:
```sh
# Install nodejs lts
nvm install --lts &&
nvm use 'lts/*' && # LTS v12.x
```
to
```sh
# install nodejs v12
nvm install v12.19.0 && nvm use v12.19.0 &&
```
followed by running ` sh -x easel-driver.sh`

**Comment by shortcircuit48** [comment]
Worked for me.  Thanks

**Comment by stevewells20** [comment]
I thought it was weird as well. I haven't touched node at all in about 4 years, seems it's really taking on the Python characteristic of being too complex and crufty to have a reliable environment change, such as an upgrade or package install. Thanks for the response, I'll attempt your instructions as soon as I have access! I did have success driving the CNC with UGS, so I at least know that that is not the issue!

**Comment by samyk** [comment]
Resolved in fcbc681, let me know if that works for you @stevewells20

**Comment by samyk** [comment]
@stevewells20 please confirm if the update worked for you, closing for now

**Comment by shortcircuit48** [comment]
Working ok.
Thanks
Hamish McNab

________________________________
