### ISSUE TITLE
Error on running using crontab

### ISSUE THREAD

**Issue by socketfork** [samyk/easel-driver#15]
Hello Samy,

I seem to be having a strange issue that only occurs when trying to launch the driver on reboot using crontab.  I can run the command manually using the same commands after I'm logged in via the 'pi' user (running Buster), but for some strange reason it won't work in crontab.

I've added the logging flag to the screen command and can see the following error in the screenlog:

2021-02-17T01:49:59.803Z iris.js [id=0] Starting Easel Driver 0.3.20
2021-02-17T01:49:59.812Z Machine [id=3] Resetting
2021-02-17T01:49:59.892Z iris.js [id=0] Listening on port 1438 for secure connections from easel.inventables.com:80 ease$
2021-02-17T01:49:59.904Z iris.js [id=0] Listening on port 1338 for connections from easel.inventables.com:80 easel.inven$
2021-02-17T01:50:06.886Z Websocket Controller [id=4] Client connected via polling
2021-02-17T01:50:07.557Z Websocket Controller [id=4] Client transport changed to websocket
^Z^X^C/home/pi/easel-driver/node_modules/bindings/bindings.js:121
        throw e;
        ^

Error: The module '/home/pi/easel-driver/node_modules/@serialport/bindings/build/Release/bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:807:18)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at bindings (/home/pi/easel-driver/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/home/pi/easel-driver/node_modules/@serialport/bindings/lib/linux.js:1:36)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
/home/pi/easel-driver/node_modules/bindings/bindings.js:121
        throw e;
        ^

I'm guessing that there is some kind of version mismatch going on, but I'm unsure of how I'd approach fixing it.  Running 'node -v' after I'm logged in tells me that it's 'v12.19.0' if that's of help.  Any insight you might have into this would be helpful.

**Comment by samyk** [comment]
You could try altering the crontab so that screen itself executes `source ~/.bashrc` before the command (or if there's an argument to do this)...I'd also suggest taking the cron, running the commands up till the screen, then executing a screen session, then running the node command directly and see if you get the same error or not. If you do, try `nvm use 12` and see if it runs afterwards.

Have you installed node some other way as well? I explicitly set v12 because the serial-port library didn't seem compatible with some newer versions last I tried, but it may be now so you could also try modifying the install and re-running the install but adjusting the node version from 12 to whatever you already have installed locally.

**Comment by socketfork** [comment]
I've tried adding the `source ~/.bashrc` command in there.  I've tried it as separate lines in crontab and on the same line.  Each time it results in this grandchild failed error:

Feb 26 17:17:06 cncpi CRON[441]: (pi) CMD (source ~/.bashrc && cd ~/easel-driver && /usr/bin/screen -dmSL easel node iris.js)
Feb 26 17:18:17 cncpi CRON[409]: (CRON) error (grandchild #441 failed with exit status 127)

I don't believe so.  This image started as a clean Buster install and I've installed your driver and the UGS platform (which is a Java app).  Running `node -v` shows me v12.19.0, so it seems like this should work.

**Comment by socketfork** [comment]
Ahhh!  So, I created a new crontab entry:

`@reboot /usr/bin/screen -dmSL test node -v`

The output of that shows v10.21.3.  So that seems to be the issue.  When running in crontab, it's using an old version, but I can't figure out why that would be.  I'm not very familiar with node.js environments.  Any ideas on what is causing this?

**Comment by socketfork** [comment]
I've installed NVM for the root user and have set the default for 12.19.0 (to match the pi user).  I've also attempted to uninstall 10.21.3 (under both users), but it responds with 'N/A version is not installed...'

My screenlog is still showing that crontab is running this as version 10.21.3.  Running `nvm ls` as root doesn't show that version but when running as pi it does.  I'm totally lost on this one.

**Comment by socketfork** [comment]
Finally!  After a lot of hair-pulling and research about node environments and whatnot, I realized that cron has the ability to have it's own node version and path.  So, I changed my crontab to include these three lines:

```
@reboot PATH="/home/pi/bin:/home/pi/.config/nvm/versions/node/v12.19.0/bin"
@reboot /usr/bin/screen -dmSL test /home/pi/.config/nvm/versions/node/v12.19.0/bin/node -v
@reboot sleep 60 && cd ~/easel-driver && /usr/bin/screen -dmSL easel /home/pi/.config/nvm/versions/node/v12.19.0/bin/node iris.js
```

I would recommend removing the second line and the '-L' screen flag to prevent unnecessary logs from being written.  

Thanks for pointing me in the right direction Samy and for writing this awesome driver.  I'm excited to try using this over the network.

**Comment by samyk** [comment]
Oh nice, great find, and thank you for the update! I'll include your improvements in the driver for others!

**Comment by samyk** [comment]
Are the first two lines needed at all? Since you're now calling the direct path to the proper node version, then I wonder if the PATH= line can be removed entirely (and no need to sleep). If it can't be, we could join it on a single line so the PATH is only changing for the single command:

```cron
@reboot cd ~/easel-driver &&  PATH="/home/pi/bin:/home/pi/.config/nvm/versions/node/v12.19.0/bin" /usr/bin/screen -dmSL easel /home/pi/.config/nvm/versions/node/v12.19.0/bin/node iris.js
```

**Comment by socketfork** [comment]
That was me throwing the kitchen sink at it trying to figure it out.  I just tried your suggestion of removing the first two lines (the 2nd line was purely just from my debugging experiments) and it looks like it's running just fine.  So the final crontab entry with everything working is this one line:

`@reboot cd ~/easel-driver && /usr/bin/screen -dmS easel /home/pi/.config/nvm/versions/node/v12.19.0/bin/node iris.js`

With the fully-qualified path in there, it looks like that first "PATH" declaration was indeed redundant.  Hopefully, that helps anyone that's running into a similar problem from newer builds of the raspbian image.  

Thanks again for helping me get this working!
