### ISSUE TITLE
Issues with system service

### ISSUE THREAD

**Issue by jordansissel** [samyk/easel-driver#18]
With #17, a system service is now added -- and that's nice!

I'm using Raspberry Pi OS latest as of yesterday. Appears to be Raspbian / Debian 10.

I found a few issues:
1) sysv is incorrectly assumed  on my raspberry pi which uses systemd.
2) the init script is not executable 

```
pi@cnc:~ $ ps -p 1
  PID TTY          TIME CMD
    1 ?        00:00:11 systemd

pi@cnc:~ $ ls -l /etc/init.d/EaselDriver 
-rw-r--r-- 1 pi pi 382 Oct 27 20:00 /etc/init.d/EaselDriver
```

sysv vs systemd is detected with `pidof /sbin/init` which on my system reports 712, so the /sbin/init check doesn't seem quite right.

```
pi@cnc:~ $ pidof /sbin/init
712
```

If I can find energy in the next week or so, I'll send a patch to resolve these.

**Comment by samyk** [comment]
That'd be great and I'd be happy to merge that + your improvements in!
