### ISSUE TITLE
Driver not connecting?

### ISSUE THREAD

**Issue by Chrism622** [samyk/easel-driver#20]
Hey all!

I have been using this driver for almost a year, and it works so well! My issue is that everything I start the raspberry pi, I have to run the driver again. I have dealt with that, but.. the past few days I have been trying to run it, and something isn't connecting to the easel driver link provided. Could something not be working on my end? Or is it the line of code from Samy k easel driver execution? 

I hope i explained this well.

**Comment by chansanuwat** [comment]
@Chrism622 what are running to start the driver every time? I just opened a PR to fix the download of the mac driver pkg, but that should only be needed on initial setup.

**Comment by samyk** [comment]
@Chrism622 will you share the log files please? All of these files `~/screenlog.* ~/easel-driver/screenlog.*` I believe. Thanks

**Comment by samyk** [comment]
I'll close this unless there's more info that can be shared, feel free to re-open if more details can be provided.

Also the restart issue is resolved via @rlancaste's update in #27 which is merged in.
