### ISSUE TITLE
Two small issues

### ISSUE THREAD

**Issue by rlancaste** [samyk/easel-driver#26]
I have been using this driver on my Raspberry Pi for the last couple of years.  Every time I had installed it, the run on startup feature has not worked without doing some modifications.  As mentioned in another Issue, I had to edit the run.sh file.  The line that said:

 ~/.nvm/nvm.sh
 
I had to change that line to this:
 
 ~/.config/nvm/nvm.sh

After doing that, it started on startup with no problem.

However, the other day I updated the raspberry pi and ran the script again to set this up again.  I ran into a more significant issue.  During the script, it had a number of errors.  A quick google search led me to this person who  had the same issue: https://stackoverflow.com/questions/74715990/node-gyp-err-invalid-mode-ru-while-trying-to-load-binding-gyp
I had to edit the file ~/.config/nvm/versions/node/v12.19.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py
as stated in the post to change rU to r in LoadOneBuildFile()
Then I ran the script again and it worked.

This is already a really great repository, If these two problems could be fixed, I think it would be much more user friendly.

**Comment by samyk** [comment]
Happy to accept a pr

**Comment by rlancaste** [comment]
So I could send a pr that addresses the first issue, but I am not sure about how to address the second one.   The issue is in a node module used by this repo, not in this repo specifically

**Comment by rlancaste** [comment]
Maybe using a different node version ?

**Comment by rlancaste** [comment]
Looks like they did fix it: https://github.com/nodejs/gyp-next/pull/83

**Comment by rlancaste** [comment]
Ok I think this should resolve both issues: https://github.com/samyk/easel-driver/pull/27

**Comment by samyk** [comment]
Awesome, thank you for the improvements! Merged.
