### ISSUE TITLE
Driver Fails to Install - nvm is not compatible with the npm config "prefix" option: currently set to ""

### ISSUE THREAD

**Issue by Philldapill85** [samyk/easel-driver#28]
Not sure what the issue is. I had the Easel driver successfully installed in my old Pi 2B, but the OS was insanely slow, so I upgraded to a Pi 4B. New OS install (Bullseye as well as Bookworm) and the driver doesn't work on these. Looks like something has changed that has broken the install. Here's the output:

Philldapill@raspberrypi:~ $ curl https://raw.githubusercontent.com/samyk/easel-driver/master/easel-driver.sh | sh -x
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 65  63+ [ -e46  easel-driver ]      0      0 --:--:-- --:--:-- --:--:--     0
  65  4125    0     0  11178      0+  --date +%s
100  6346  100  6346    0     0  17105      0 --:--:-- --:--:-- --:--:-- 17105
+ mv easel-driver easel-driver.bak.1730665405
+ mkdir -p easel-driver
+ cd easel-driver
.
.
.
(Everything is fine up 'til now, omitted due to character limit)
.
.
.
./node_modules/inflight/LICENSE
./node_modules/inflight/inflight.js
./node_modules/inflight/README.md
./node_modules/inflight/package.json
./package-lock.json
./package.json
./lib
./lib/event_dispatcher.js
./lib/gcode_parser.js
./lib/websocket_controller.js
./lib/interval.js
./lib/rate_tracker.js
./lib/serial_port_controller.js
./lib/error_handler.js
./lib/firmware_uploader.js
./lib/machine.js
./lib/avrdude_parser.js
./lib/debugger.js
./lib/parser.js
./iris.js
29816 blocks
+ cp -r lib iris.js package.json ssl avrdude/etc/avrdude.conf ../
+ cd ..
+ mkdir lib/etc
+ mv avrdude.conf lib/etc
+ ln -s lib/etc etc
+ perl -pi -e if (/var PLATFORMS/) { $x = chr(39); print; $_ = "\t${x}Linux${x}: {\n\t\troot: ${x}/usr/bin/avrdude${x},\n\t\texecutable: ${x}/usr/bin/avrdude${x},\n\t\tconfig: path.join(__dirname, ${x}etc/avrdude.conf${x})\n\t},\n"; } lib/firmware_uploader.js
+ perl -pi -e if (/callback\(ports/) { print << "EOF"
        ports.forEach(function(part, i) {
          if (this[i].manufacturer === "1a86")
            this[i].manufacturer = "FTDI";
          if (this[i].manufacturer === "Silicon Labs")
            this[i].manufacturer = "FTDI";
          if (this[i].vendorId === "1a86")
            this[i].vendorId = "0403";
           if (this[i].vendorId === "10c4")
            this[i].vendorId = "0403";           
        }, ports);
EOF
} lib/serial_port_controller.js
+ perl -pi -e if (/that\.dispatchEvent\(.unknown.\, message/) { print << "EOF"
        if (message.includes(\x{027}FluidNC\x{027}) && !isMachineConnected){
           onMachineConnected(\x{027}Grbl 1.1g [\\\x{027}\$\\\x{027} for help]\x{027});
        }
EOF
} lib/machine.js
+ curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh
+ bash -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13527  100 13527    0     0  36658      0 --:--:-- --:--:-- --:--:-- 36658
=> nvm is already installed in /home/Philldapill/.config/nvm, trying to update using git
=> => Compressing and cleaning up git repository

=> nvm source string already in /home/Philldapill/.bashrc
=> bash_completion source string already in /home/Philldapill/.bashrc
/usr/bin/env: ‘node’: No such file or directory
nvm is not compatible with the npm config "prefix" option: currently set to ""
Run `nvm use --delete-prefix v18.20.4 --silent` to unset it.
=> Close and reopen your terminal to start using nvm or run the following to use it now:

export NVM_DIR="$HOME/.config/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
+ [ ! -e /home/Philldapill/.config/nvm ]
+ [ -s /home/Philldapill/.config/nvm/nvm.sh ]
+ . /home/Philldapill/.config/nvm/nvm.sh
+ NVM_SCRIPT_SOURCE=/usr/bin/sh
+ [ -z  ]
+ export NVM_CD_FLAGS=
+ nvm_is_zsh
+ [ -n  ]
+ [ -z /home/Philldapill/.config/nvm ]
+ unset NVM_SCRIPT_SOURCE
+ nvm_process_parameters
+ local NVM_AUTO_MODE
+ NVM_AUTO_MODE=use
+ nvm_supports_source_options
+ . /dev/stdin yes
+ [ _ = _yes ]
+ nvm_auto use
+ local NVM_CURRENT
+ nvm_ls_current
+ local NVM_LS_CURRENT_NODE_PATH
+ command which node
+ NVM_LS_CURRENT_NODE_PATH=
+ nvm_echo none
+ command printf %s\n none
+ NVM_CURRENT=none
+ local NVM_MODE
+ NVM_MODE=use
+ local VERSION
+ [ _use = _install ]
+ [ _use = _use ]
+ [ _none = _none ]
+ nvm_resolve_local_alias default
+ VERSION=v18.20.4
+ [ -n v18.20.4 ]
+ nvm use --silent v18.20.4
+ [ 3 -lt 1 ]
+ local DEFAULT_IFS
+ nvm_echo t
+ + command tr t \t
command printf %s\n t
+ DEFAULT_IFS= 	

+ [ xs != xs ]
+ [  	
 !=  	
 ]
+ local COMMAND
+ COMMAND=use
+ shift
+ local VERSION
+ local ADDITIONAL_PARAMETERS
+ local PROVIDED_VERSION
+ local NVM_USE_SILENT
+ NVM_USE_SILENT=0
+ local NVM_DELETE_PREFIX
+ NVM_DELETE_PREFIX=0
+ local NVM_LTS
+ [ 2 -ne 0 ]
+ NVM_USE_SILENT=1
+ shift
+ [ 1 -ne 0 ]
+ [ -n v18.20.4 ]
+ PROVIDED_VERSION=v18.20.4
+ shift
+ [ 0 -ne 0 ]
+ [ -n  ]
+ [ -z v18.20.4 ]
+ nvm_match_version v18.20.4
+ local NVM_IOJS_PREFIX
+ nvm_iojs_prefix
+ nvm_echo iojs
+ command printf %s\n iojs
+ NVM_IOJS_PREFIX=iojs
+ local PROVIDED_VERSION
+ PROVIDED_VERSION=v18.20.4
+ nvm_version v18.20.4
+ local PATTERN
+ PATTERN=v18.20.4
+ local VERSION
+ [ -z v18.20.4 ]
+ [ v18.20.4 = current ]
+ local NVM_NODE_PREFIX
+ nvm_node_prefix
+ nvm_echo node
+ command printf %s\n node
+ NVM_NODE_PREFIX=node
+ nvm_ls v18.20.4
+ local PATTERN
+ PATTERN=v18.20.4
+ local VERSIONS
+ VERSIONS=
+ [ v18.20.4 = current ]
+ local NVM_IOJS_PREFIX
+ command tail -1
+ nvm_iojs_prefix
+ nvm_echo iojs
+ command printf %s\n iojs
+ NVM_IOJS_PREFIX=iojs
+ local NVM_NODE_PREFIX
+ nvm_node_prefix
+ nvm_echo node
+ command printf %s\n node
+ NVM_NODE_PREFIX=node
+ local NVM_VERSION_DIR_IOJS
+ nvm_version_dir iojs
+ local NVM_WHICH_DIR
+ NVM_WHICH_DIR=iojs
+ [ -z iojs ]
+ [ iojs = new ]
+ [ _iojs = _iojs ]
+ nvm_echo /home/Philldapill/.config/nvm/versions/io.js
+ command printf %s\n /home/Philldapill/.config/nvm/versions/io.js
+ NVM_VERSION_DIR_IOJS=/home/Philldapill/.config/nvm/versions/io.js
+ local NVM_VERSION_DIR_NEW
+ nvm_version_dir new
+ local NVM_WHICH_DIR
+ NVM_WHICH_DIR=new
+ [ -z new ]
+ [ new = new ]
+ nvm_echo /home/Philldapill/.config/nvm/versions/node
+ command printf %s\n /home/Philldapill/.config/nvm/versions/node
+ NVM_VERSION_DIR_NEW=/home/Philldapill/.config/nvm/versions/node
+ local NVM_VERSION_DIR_OLD
+ nvm_version_dir old
+ local NVM_WHICH_DIR
+ NVM_WHICH_DIR=old
+ [ -z old ]
+ [ old = new ]
+ [ _old = _iojs ]
+ [ _old = _old ]
+ nvm_echo /home/Philldapill/.config/nvm
+ command printf %s\n /home/Philldapill/.config/nvm
+ NVM_VERSION_DIR_OLD=/home/Philldapill/.config/nvm
+ nvm_resolve_local_alias v18.20.4
+ [ -z v18.20.4 ]
+ local VERSION
+ local EXIT_CODE
+ nvm_resolve_alias v18.20.4
+ [ -z v18.20.4 ]
+ local PATTERN
+ PATTERN=v18.20.4
+ local ALIAS
+ ALIAS=v18.20.4
+ local ALIAS_TEMP
+ local SEEN_ALIASES
+ SEEN_ALIASES=v18.20.4
+ true
+ nvm_alias v18.20.4
+ nvm_echo
+ command printf %s\n 
+ ALIAS_TEMP=
+ [ -z  ]
+ break
+ [ -n v18.20.4 ]
+ [ _v18.20.4 != _v18.20.4 ]
+ nvm_validate_implicit_alias v18.20.4
+ return 2
+ VERSION=
+ EXIT_CODE=2
+ [ -z  ]
+ return 2
+ nvm_ensure_version_prefix v18.20.4
+ local NVM_VERSION
+ nvm_strip_iojs_prefix v18.20.4
+ local NVM_IOJS_PREFIX
+ + command sednvm_iojs_prefix
+  -envm_echo iojs
 s/^\([0-9]\)/v\1/g
+ command printf %s\n iojs
+ NVM_IOJS_PREFIX=iojs
+ [ v18.20.4 = iojs ]
+ nvm_echo v18.20.4
+ command printf %s\n v18.20.4
+ NVM_VERSION=v18.20.4
+ nvm_is_iojs_version v18.20.4
+ return 1
+ nvm_echo v18.20.4
+ command printf %s\n v18.20.4
+ PATTERN=v18.20.4
+ [ v18.20.4 = N/A ]
+ local NVM_PATTERN_STARTS_WITH_V
+ NVM_PATTERN_STARTS_WITH_V=true
+ [ true = true ]
+ nvm_num_version_groups v18.20.4
+ local VERSION
+ VERSION=v18.20.4
+ VERSION=18.20.4
+ VERSION=18.20.4
+ [ -z 18.20.4 ]
+ local NVM_NUM_DOTS
+ nvm_echo 18.20.4
+ command printf %s\n 18.20.4+ 
command sed -e s/[^\.]//g
+ NVM_NUM_DOTS=..
+ local NVM_NUM_GROUPS
+ NVM_NUM_GROUPS=...
+ nvm_echo 3
+ command printf %s\n 3
+ [ _3 = _3 ]
+ nvm_is_version_installed v18.20.4
+ [ -n v18.20.4 ]
+ nvm_version_path v18.20.4
+ [ -x /home/Philldapill/.config/nvm/versions/node/v18.20.4/bin/node ]
+ VERSIONS=v18.20.4
+ [  = true ]
+ [ -z v18.20.4 ]
+ nvm_echo v18.20.4
+ command printf %s\n v18.20.4
+ VERSION=v18.20.4
+ [ -z v18.20.4 ]
+ [ _v18.20.4 = _N/A ]
+ nvm_echo v18.20.4
+ command printf %s\n v18.20.4
+ VERSION=v18.20.4
+ [ -z v18.20.4 ]
+ [ _v18.20.4 = _system ]
+ [ _v18.20.4 = _∞ ]
+ [ v18.20.4 = N/A ]
+ nvm_ensure_version_installed v18.20.4
+ local PROVIDED_VERSION
+ PROVIDED_VERSION=v18.20.4
+ [ v18.20.4 = system ]
+ local LOCAL_VERSION
+ local EXIT_CODE
+ nvm_version v18.20.4
+ local PATTERN
+ PATTERN=v18.20.4
+ local VERSION
+ [ -z v18.20.4 ]
+ [ v18.20.4 = current ]
+ local NVM_NODE_PREFIX
+ nvm_node_prefix
+ nvm_echo node
+ command printf %s\n node
+ NVM_NODE_PREFIX=node
+ nvm_ls v18.20.4
+ local PATTERN
+ PATTERN=v18.20.4+ 
+ localcommand VERSIONS
 tail -1
+ VERSIONS=
+ [ v18.20.4 = current ]
+ local NVM_IOJS_PREFIX
+ nvm_iojs_prefix
+ nvm_echo iojs
+ command printf %s\n iojs
+ NVM_IOJS_PREFIX=iojs
+ local NVM_NODE_PREFIX
+ nvm_node_prefix
+ nvm_echo node
+ command printf %s\n node
+ NVM_NODE_PREFIX=node
+ local NVM_VERSION_DIR_IOJS
+ nvm_version_dir iojs
+ local NVM_WHICH_DIR
+ NVM_WHICH_DIR=iojs
+ [ -z iojs ]
+ [ iojs = new ]
+ [ _iojs = _iojs ]
+ nvm_echo /home/Philldapill/.config/nvm/versions/io.js
+ command printf %s\n /home/Philldapill/.config/nvm/versions/io.js
+ NVM_VERSION_DIR_IOJS=/home/Philldapill/.config/nvm/versions/io.js
+ local NVM_VERSION_DIR_NEW
+ nvm_version_dir new
+ local NVM_WHICH_DIR
+ NVM_WHICH_DIR=new
+ [ -z new ]
+ [ new = new ]
+ nvm_echo /home/Philldapill/.config/nvm/versions/node
+ command printf %s\n /home/Philldapill/.config/nvm/versions/node
+ NVM_VERSION_DIR_NEW=/home/Philldapill/.config/nvm/versions/node
+ local NVM_VERSION_DIR_OLD
+ nvm_version_dir old
+ local NVM_WHICH_DIR
+ NVM_WHICH_DIR=old
+ [ -z old ]
+ [ old = new ]
+ [ _old = _iojs ]
+ [ _old = _old ]
+ nvm_echo /home/Philldapill/.config/nvm
+ command printf %s\n /home/Philldapill/.config/nvm
+ NVM_VERSION_DIR_OLD=/home/Philldapill/.config/nvm
+ nvm_resolve_local_alias v18.20.4
+ [ -z v18.20.4 ]
+ local VERSION
+ local EXIT_CODE
+ nvm_resolve_alias v18.20.4
+ [ -z v18.20.4 ]
+ local PATTERN
+ PATTERN=v18.20.4
+ local ALIAS
+ ALIAS=v18.20.4
+ local ALIAS_TEMP
+ local SEEN_ALIASES
+ SEEN_ALIASES=v18.20.4
+ true
+ nvm_alias v18.20.4
+ nvm_echo
+ command printf %s\n 
+ ALIAS_TEMP=
+ [ -z  ]
+ break
+ [ -n v18.20.4 ]
+ [ _v18.20.4 != _v18.20.4 ]
+ nvm_validate_implicit_alias v18.20.4
+ return 2
+ VERSION=
+ EXIT_CODE=2
+ [ -z  ]
+ return 2
+ nvm_ensure_version_prefix v18.20.4
+ local NVM_VERSION
+ nvm_strip_iojs_prefix v18.20.4
+ local NVM_IOJS_PREFIX
+ command sed -e s/^\([0-9]\)/v\1/g
+ nvm_iojs_prefix
+ nvm_echo iojs
+ command printf %s\n iojs
+ NVM_IOJS_PREFIX=iojs
+ [ v18.20.4 = iojs ]
+ nvm_echo v18.20.4
+ command printf %s\n v18.20.4
+ NVM_VERSION=v18.20.4
+ nvm_is_iojs_version v18.20.4
+ return 1
+ nvm_echo v18.20.4
+ command printf %s\n v18.20.4
+ PATTERN=v18.20.4
+ [ v18.20.4 = N/A ]
+ local NVM_PATTERN_STARTS_WITH_V
+ NVM_PATTERN_STARTS_WITH_V=true
+ [ true = true ]
+ nvm_num_version_groups v18.20.4
+ local VERSION
+ VERSION=v18.20.4
+ VERSION=18.20.4
+ VERSION=18.20.4
+ [ -z 18.20.4 ]
+ local NVM_NUM_DOTS
+ nvm_echo 18.20.4
+ command printf %s\n 18.20.4
+ command sed -e s/[^\.]//g
+ NVM_NUM_DOTS=..
+ local NVM_NUM_GROUPS
+ NVM_NUM_GROUPS=...
+ nvm_echo 3
+ command printf %s\n 3
+ [ _3 = _3 ]
+ nvm_is_version_installed v18.20.4
+ [ -n v18.20.4 ]
+ nvm_version_path v18.20.4
+ [ -x /home/Philldapill/.config/nvm/versions/node/v18.20.4/bin/node ]
+ VERSIONS=v18.20.4
+ [  = true ]
+ [ -z v18.20.4 ]
+ nvm_echo v18.20.4
+ command printf %s\n v18.20.4
+ VERSION=v18.20.4
+ [ -z v18.20.4 ]
+ [ _v18.20.4 = _N/A ]
+ nvm_echo v18.20.4
+ command printf %s\n v18.20.4
+ LOCAL_VERSION=v18.20.4
+ EXIT_CODE=0
+ local NVM_VERSION_DIR
+ [ 0 != 0 ]
+ nvm_is_version_installed v18.20.4
+ [ -n v18.20.4 ]
+ nvm_version_path v18.20.4
+ [ -x /home/Philldapill/.config/nvm/versions/node/v18.20.4/bin/node ]
+ local NVM_VERSION_DIR
+ nvm_version_path v18.20.4
+ local VERSION
+ VERSION=v18.20.4
+ [ -z v18.20.4 ]
+ nvm_is_iojs_version v18.20.4
+ return 1
+ nvm_version_greater 0.12.0 v18.20.4
+ command awk BEGIN {
    if (ARGV[1] == "" || ARGV[2] == "") exit(1)
    split(ARGV[1], a, /\./);
    split(ARGV[2], b, /\./);
    for (i=1; i<=3; i++) {
      if (a[i] && a[i] !~ /^[0-9]+$/) exit(2);
      if (b[i] && b[i] !~ /^[0-9]+$/) { exit(0); }
      if (a[i] < b[i]) exit(3);
      else if (a[i] > b[i]) exit(0);
    }
    exit(4)
  } 0.12.0 18.20.4
+ nvm_version_dir new
+ local NVM_WHICH_DIR
+ NVM_WHICH_DIR=new
+ [ -z new ]
+ [ new = new ]
+ nvm_echo /home/Philldapill/.config/nvm/versions/node
+ command printf %s\n /home/Philldapill/.config/nvm/versions/node
+ nvm_echo /home/Philldapill/.config/nvm/versions/node/v18.20.4
+ command printf %s\n /home/Philldapill/.config/nvm/versions/node/v18.20.4
+ NVM_VERSION_DIR=/home/Philldapill/.config/nvm/versions/node/v18.20.4
+ nvm_change_path /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games /bin /home/Philldapill/.config/nvm/versions/node/v18.20.4
+ [ -z /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games ]
+ nvm_echo /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games
+ command+  printf %s\nnvm_grep /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games
 -q /home/Philldapill/.config/nvm/[^/]*/bin
+ GREP_OPTIONS= command grep -q /home/Philldapill/.config/nvm/[^/]*/bin
+ nvm_echo /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games
+ nvm_grep -q /home/Philldapill/.config/nvm/versions/[^/]*/[^/]*/bin
+ command+ GREP_OPTIONS= command printf grep %s\n -q /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games /home/Philldapill/.config/nvm/versions/[^/]*/[^/]*/bin

+ nvm_echo /home/Philldapill/.config/nvm/versions/node/v18.20.4/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games
+ command printf %s\n /home/Philldapill/.config/nvm/versions/node/v18.20.4/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games
+ PATH=/home/Philldapill/.config/nvm/versions/node/v18.20.4/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games
+ nvm_has manpath
+ type manpath
+ [ -z  ]
+ local MANPATH
+ manpath
+ MANPATH=/home/Philldapill/.config/nvm/versions/node/v18.20.4/share/man:/usr/local/man:/usr/local/share/man:/usr/share/man
+ nvm_change_path /home/Philldapill/.config/nvm/versions/node/v18.20.4/share/man:/usr/local/man:/usr/local/share/man:/usr/share/man /share/man /home/Philldapill/.config/nvm/versions/node/v18.20.4
+ [ -z /home/Philldapill/.config/nvm/versions/node/v18.20.4/share/man:/usr/local/man:/usr/local/share/man:/usr/share/man ]
+ nvm_echo /home/Philldapill/.config/nvm/versions/node/v18.20.4/share/man:/usr/local/man:/usr/local/share/man:/usr/share/man
+ command+  printf %s\nnvm_grep /home/Philldapill/.config/nvm/versions/node/v18.20.4/share/man:/usr/local/man:/usr/local/share/man:/usr/share/man
 -q /home/Philldapill/.config/nvm/[^/]*/share/man
+ GREP_OPTIONS= command grep -q /home/Philldapill/.config/nvm/[^/]*/share/man
+ nvm_echo /home/Philldapill/.config/nvm/versions/node/v18.20.4/share/man:/usr/local/man:/usr/local/share/man:/usr/share/man
+ command printf %s\n /home/Philldapill/.config/nvm/versions/node/v18.20.4/share/man:/usr/local/man:/usr/local/share/man:/usr/share/man
+ nvm_grep -q /home/Philldapill/.config/nvm/versions/[^/]*/[^/]*/share/man
+ GREP_OPTIONS= command grep -q /home/Philldapill/.config/nvm/versions/[^/]*/[^/]*/share/man
+ nvm_echo /home/Philldapill/.config/nvm/versions/node/v18.20.4/share/man:/usr/local/man:/usr/local/share/man:/usr/share/man
+ command printf %s\n /home/Philldapill/.config/nvm/versions/node/v18.20.4/share/man:/usr/local/man:/usr/local/share/man:/usr/share/man
+ nvm_grep -Eq (^|:)(/usr(/local)?)?/share/man:.*/home/Philldapill/.config/nvm/[^/]*/share/man
+ GREP_OPTIONS= command grep -Eq (^|:)(/usr(/local)?)?/share/man:.*/home/Philldapill/.config/nvm/[^/]*/share/man
+ + nvm_grep -Eq (^|:)(/usr(/local)?)?/share/man:.*/home/Philldapill/.config/nvm/versions/[^/]*/[^/]*/share/man
nvm_echo /home/Philldapill/.config/nvm/versions/node/v18.20.4/share/man:/usr/local/man:/usr/local/share/man:/usr/share/man
+ GREP_OPTIONS= command grep -Eq (^|:)(/usr(/local)?)?/share/man:.*/home/Philldapill/.config/nvm/versions/[^/]*/[^/]*/share/man
+ command printf %s\n /home/Philldapill/.config/nvm/versions/node/v18.20.4/share/man:/usr/local/man:/usr/local/share/man:/usr/share/man
+ nvm_echo /home/Philldapill/.config/nvm/versions/node/v18.20.4/share/man:/usr/local/man:/usr/local/share/man:/usr/share/man
+ command printf %s\n /home/Philldapill/.config/nvm/versions/node/v18.20.4/share/man:/usr/local/man:/usr/local/share/man:/usr/share/man
+ command sed -e s#/home/Philldapill/.config/nvm/[^/]*/share/man[^:]*#/home/Philldapill/.config/nvm/versions/node/v18.20.4/share/man# -e s#/home/Philldapill/.config/nvm/versions/[^/]*/[^/]*/share/man[^:]*#/home/Philldapill/.config/nvm/versions/node/v18.20.4/share/man#
+ MANPATH=/home/Philldapill/.config/nvm/versions/node/v18.20.4/share/man:/usr/local/man:/usr/local/share/man:/usr/share/man
+ export MANPATH
+ export PATH
+ hash -r
+ export NVM_BIN=/home/Philldapill/.config/nvm/versions/node/v18.20.4/bin
+ export NVM_INC=/home/Philldapill/.config/nvm/versions/node/v18.20.4/include/node
+ [  = true ]
+ local NVM_USE_OUTPUT
+ NVM_USE_OUTPUT=
+ [ 1 -ne 1 ]
+ [ _v18.20.4 != _system ]
+ local NVM_USE_CMD
+ NVM_USE_CMD=nvm use --delete-prefix
+ [ -n v18.20.4 ]
+ NVM_USE_CMD=nvm use --delete-prefix v18.20.4
+ [ 1 -eq 1 ]
+ NVM_USE_CMD=nvm use --delete-prefix v18.20.4 --silent
+ nvm_die_on_prefix 0 nvm use --delete-prefix v18.20.4 --silent
+ local NVM_DELETE_PREFIX
+ NVM_DELETE_PREFIX=0
+ local NVM_COMMAND
+ NVM_COMMAND=nvm use --delete-prefix v18.20.4 --silent
+ [ -z nvm use --delete-prefix v18.20.4 --silent ]
+ [ -n  ]
+ local NVM_NPM_CONFIG_PREFIX_ENV
+ command env
+ nvm_grep -i NPM_CONFIG_PREFIX
+ GREP_OPTIONS= command grep -i NPM_CONFIG_PREFIX
+ command awk -F = {print $1}
+ command tail -1
+ NVM_NPM_CONFIG_PREFIX_ENV=
+ [ -n  ]
+ nvm_has npm
+ type npm
+ local NVM_NPM_PREFIX
+ npm config --loglevel=warn get prefix
/usr/bin/env: ‘node’: No such file or directory
+ NVM_NPM_PREFIX=
+ nvm_tree_contains_path /home/Philldapill/.config/nvm 
+ [ _0 = _1 ]
+ nvm deactivate
+ nvm_err nvm is not compatible with the npm config "prefix" option: currently set to ""
+ nvm_echo nvm is not compatible with the npm config "prefix" option: currently set to ""
+ command printf %s\n nvm is not compatible with the npm config "prefix" option: currently set to ""
nvm is not compatible with the npm config "prefix" option: currently set to ""
+ nvm_has npm
+ type npm
+ nvm_err Run `nvm use --delete-prefix v18.20.4 --silent` to unset it.
+ nvm_echo Run `nvm use --delete-prefix v18.20.4 --silent` to unset it.
+ command printf %s\n Run `nvm use --delete-prefix v18.20.4 --silent` to unset it.
Run `nvm use --delete-prefix v18.20.4 --silent` to unset it.
+ return 10
+ return 11
+ true
+ echo Almost done! Do you want Easel driver to run on startup (will install system service) [yn]: 
Almost done! Do you want Easel driver to run on startup (will install system service) [yn]: 
+ read yn
y
+ check_init
sh: 189: check_init: not found
+ create_start_script
+ pwd
+ driverdir=/home/Philldapill/easel-driver
+ touch /home/Philldapill/easel-driver/run.sh
+ chmod +x /home/Philldapill/easel-driver/run.sh
+ cat
+ install_service
+ [  = 1 ]
+ touch /home/Philldapill/easel-driver/EaselDriver
+ whoami
+ whoami
+ cat
+ sudo mv /home/Philldapill/easel-driver/EaselDriver /etc/init.d/
+ sudo chkconfig --add EaselDriver
sudo: chkconfig: command not found
+ sudo chkconfig --level 2345 EaselDriver on
sudo: chkconfig: command not found
+ break
+ screen -L -dmS easel node iris.js
+ sleep 3
+ echo \n\n\n

+ tail screenlog.0
Cannot exec 'node': No such file or directory
+ echo \n\nDone! Easel driver running in background. Run `screen -r` to bring it to foreground.

Done! Easel driver running in background. Run `screen -r` to bring it to foreground.
Philldapill@raspberrypi:~ $

**Comment by samyk** [comment]
Looks like the node or nvm piece either didn't install or activate properly...don't have a moment to look at this right now but happy to accept PRs.

Did you already have nvm/node installed? If so, maybe there was a conflict or an update to support a pre-existing install would be nice. This is in your logs:
```
=> nvm is already installed in /home/Philldapill/.config/nvm, trying to update using git
=> => Compressing and cleaning up git repository
=> nvm source string already in /home/Philldapill/.bashrc
=> bash_completion source string already in /home/Philldapill/.bashrc
/usr/bin/env: ‘node’: No such file or directory
nvm is not compatible with the npm config "prefix" option: currently set to ""
Run nvm use --delete-prefix v18.20.4 --silent to unset it.
=> Close and reopen your terminal to start using nvm or run the following to use it now:
```

**Comment by Philldapill85** [comment]
This was a fresh install of the latest Raspbian as of 10/22/24. Not sure why, but a fresh install of nvm/node fixed it for some reason.

I don't know how you accomplish what you do in 24 hour days, but it's appreciated immensely!
