### ISSUE TITLE
different serial port js file

### ISSUE THREAD

**Issue by maly-miller** [samyk/easel-driver#7]
hi samy

my file looks different than what you have in the readme

i am missing the parser line and the baudrate is between brackets. should i add them?
 currentComName = comName;
    var thisPort = new SerialPort(
      comName,
      { baudRate: config.baud },
      function (error) {
        if (error !== null) {
          logger.log("ERROR: " + error, Debugger.logger.RED);
        }

**Comment by IKnowNow** [comment]
Samy,
After I change the file, do I need to rebuild the application?

**Comment by samyk** [comment]
You shouldn't have to change any of the files manually. Just run the easel-driver and it should handle everything for you. Can you test the latest version and let me know if it works for you?

**Comment by samyk** [comment]
Please re-open this if you still have issues. Thanks!
